name: Flutter

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.0.2
      - name: create default flutter project
        run: flutter create example
               
      - name: Install dependencies
        run: |
          cd example
          flutter pub get
          

      - name: Analyze project source
        run: |
          cd example
          dart analyze

      - name: Run tests
        run: |
          cd example
          flutter test
