name: Flutter

on:
  push:
    branches: [main, v*]
  pull_request:
    branches: [main, v*]
  schedule:
    # https://crontab.guru/#40_10_*_*_*
    - cron: '40 10 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stable:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - windows-latest
          - macos-latest # Apple M1 Silicon
          - macos-13 # Intel macOS
        version:
          - latest
          - 3.27.0
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          version: ${{ inputs.version }}
          channel: stable

      - name: Dart version
        run: dart --version
      - name: Flutter version
        run: flutter --version
      - name: Flutter doctor
        run: flutter doctor

      - name: Run hello world
        run: |
          echo "main() { print('hello world'); }" > hello.dart
          dart hello.dart

  beta:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - windows-latest
          - macos-latest # Apple M1 Silicon
          - macos-13 # Intel macOS
        version:
          - latest
          - 3.27.0-0.1.pre
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          version: ${{ inputs.version }}
          channel: beta

      - name: Dart version
        run: dart --version
      - name: Flutter version
        run: flutter --version
      - name: Flutter doctor
        run: flutter doctor

      - name: Run hello world
        run: |
          echo "main() { print('hello world'); }" > hello.dart
          dart hello.dart
